[settings]
token = "OTI3ODc0NTQ4MTg2MDkxNTMy.YdQkgw.KalZPwYuI-c1we7BR7c_jidFRY8" # Secret bot token
prefix = "^" # Commands prefix
activity = "TicketBot | Ready to work!" # Bot activity status
online_status = "dnd" # Online status types: "online", "idle", "dnd (Do Not Disturb)", "invisible", "offline"
ticket_category_id = "927876878751113216" # ID of the category in which the tickets will be created
ticket_is_already_opened = "U have already opened ticket!" # Private message received by a user trying to create a new ticket while already having one open

[ticket_create_embed]
color = "#fcba03" # HEX color
title = "Ticket" # Embed title
description = "Create ticket by clicking button below!" # Description of the embed in create ticket channel
button_name = "Create Ticket" # Name of the button

[ticket_embed]
description = "Hi %user%, please describe your problem to us." # Description of embed in the ticket channel
close_ticket = "Click to close ticket!" # Name of the button
